function axesComponent = CreateAxesComponent( parent, position, yAxisLocation )

axesComponent = axes(...
    'Parent',parent,...
    'Units','normalized',...
    'Position', position,...
    'FontSize',10,...
    'XTick',[],...
    'XTickLabel',[],...
    'XTickLabelMode','manual',...
    'XTickMode','manual',...
    'YAxisLocation',yAxisLocation);
    
    