function panel = CreatePanel( position, figureHandle, title )

panel = uipanel('BorderType','etchedin',...
		...%'BackgroundColor',panelColor,...
        'Units','normalized',...
        'Position',position,...
		'Parent',figureHandle,...
        'Title',title);