function textComponent = CreateCheckboxComponent( parent, position, string )

textComponent = uicontrol(...
    'Parent', parent,...
    'Style', 'checkbox',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'FontSize',13.9 );
    
    