function textComponent = CreateTextComponent( parent, position, string )

textComponent = uicontrol(...
    'Parent', parent,...
    'Style', 'text',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'HorizontalAlignment','left',...
    'FontSize',10 );
    
    