function textComponent = CreateToggleButton( parent, position, string )

textComponent = uicontrol(...
    'Parent', parent,...
    'Style', 'toggle',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'FontSize',13.9 );
    
    