function pushButtonHandle = CreatePushButtonComponent( parent, position, string)

pushButtonHandle = uicontrol('Parent', parent,...
    'Style', 'pushbutton',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'FontSize',12);

