function editBoxComponent = CreateEditBoxComponent( parent, position, string )

editBoxComponent = uicontrol(...
    'Parent', parent,...
    'Style', 'edit',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'HorizontalAlignment','center',...
    'FontSize',13.9 );
    
    