function listboxHandle = CreateListboxComponent( parent, position, string)

listboxHandle = uicontrol('Parent', parent,...
    'Style', 'listbox',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'FontSize',11);
