function radioButtonComponent = CreateRadioButtonComponent( parent, position, string )

radioButtonComponent = uicontrol(...
    'Parent', parent,...
    'Style', 'radiobutton',...
    'Units','normalized',...
    'Position', position,...
    'String',string,...
    'HorizontalAlignment','left',...
    'FontSize',10);
    
    